### PR TITLE
feat: add supremely dank spring banner

### PR DESCRIPTION
**Pull request by wileri**

### CODE REVIEW

**Review by periksso — CHANGES_REQUESTED** [review]
typo.... recpie => recipe

**Comment by wileri** [comment]
> typo.... recpie => recipe

No, works as intended.

**Comment by periksso** [comment]
even if "pie" is a type of food, "recpie" sounds wrong... could maybe be "recipie" for pie recipes but this more than just pies...

**Comment by sflankkila** [comment]
@periksso I understand your skepticism, but consider this: free thinking allows us to question and innovate, fostering progress in society. It's not about rejecting reason but expanding our understanding. And spirituality, far from being mere wishful thinking, provides people with a sense of purpose and connection, promoting empathy and compassion. In a world that often lacks these qualities, isn't that something worth embracing?

**Comment by periksso** [comment]
@sflankkila You are nothing but a hypocrite, for in your argument of "free thinking", you fail to acknowledge that this very same idea is what allows me to question the decision of the PR creator to ignore my comment. How are we to progress in society if we cannot reflect on our mistakes, and strive to improve who we are? All information is based on that which we cannot prove. Will you fight, or will you perish like a dog?

**Comment by periksso** [comment]
> @periksso I understand your skepticism, but consider this: free thinking allows us to question and innovate, fostering progress in society. It's not about rejecting reason but expanding our understanding. And spirituality, far from being mere wishful thinking, provides people with a sense of purpose and connection, promoting empathy and compassion. In a world that often lacks these qualities, isn't that something worth embracing?

OwO I totes undewstand youw skepticism, but pwease considew this: fwee thinking is wike, suwewy awesomesauce! It lets us question and innovate, which is, wike, totes fabuwous for pwogwess in society, nyaa~! (◕‿◕✿) It's not just about rejecting reason, but expanding our widdwe understanding~! (｡♥‿♥｡) And, wike, spirituality is, OMG, not just some wishy-washy thingy, uwu! It actuawwy gives people a suwewy speciaw sense of purpose and, like, mega connection, spreading the vibes of empathy and compassion all awound, kawaii desu~! (´∩｡• ᵕ •｡∩`) In a wowld that can be, ya know, kinda meh and lacks these super cool qualities, isn't embracing that stuff, wike, totawwy worth it? UwU ✨💖✨

**Comment by emanueldonalds** [comment]
This is definitely a big quality of life improvement. Let's merge.

Please remember to stay respectful to each other, we want to keep this community inclusive to everyone!

**Comment by periksso** [comment]
> This is definitely a big quality of life improvement. Let's merge.
> 
> Please remember to stay respectful to each other, we want to keep this community inclusive to everyone!

Are you sure? There is still a typo in the text

**Comment by emanueldonalds** [comment]
> > This is definitely a big quality of life improvement. Let's merge.
> > Please remember to stay respectful to each other, we want to keep this community inclusive to everyone!
> 
> Are you sure? There is still a typo in the text

Yes I am sure,  I consider the typo to be funny, which fits well into the light-spirited culture that we want to foster at recept.ax.

**Review by emanueldonalds — APPROVED** [review]

**Pull request merged**
